### ISSUE TITLE
[$350] Support for embedded scene

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#260]
Similar to #259 , we want to be able to support embedded Spark "scenes" inside tables.  Have a look at the current sample from pxscene.org:

![screen_shot_2018-12-23_at_7_10_42_pm](https://user-images.githubusercontent.com/21790/50381906-b9258780-06e6-11e9-9554-e16b8e7d8f32.jpg)

**Comment by jmgasper** [comment]
@billsedison - Check my fork for the latest:  https://github.com/jmgasper/pxscene

**Comment by billsedison** [comment]
@jmgasper 

A problem, for a table, if there is only 1 column contains the 1 embedded scene or image, that's fine.
![image](https://user-images.githubusercontent.com/5657467/50413449-39183280-084a-11e9-8083-a8a25fa40e60.png)


But if we embedded 2 or more embedded scenes or images in columns of the same row, then the table cell might be cluttered because the size of the embedded scenes or images are too large, then it's impossible to make enough room for each embedded scene/image and keep the entire table to be viewable in the screen.


![image](https://user-images.githubusercontent.com/5657467/50413513-acba3f80-084a-11e9-875f-f9ac97bfb557.png)

In this case, how should we handle it?

**Comment by jmgasper** [comment]
For now, we can leave this as-is.  I'm not entirely sure what the client will want here, so we'll go with this and get feedback from them as to what to do.

**Comment by billsedison** [comment]
OK
