### ISSUE TITLE
[$400] Investigate supporting strike-through 

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#261]
Currently, Github supports strike-through with two tildes:

~~strikethrough~~

This doesn't appear to work in Spark.  I'm not sure if the text formatting available to Spark apps allows for this, but I'd like to investigate and at least let the client know if this is something that is blocked due to Spark incompatibility.

**Comment by billsedison** [comment]
@jmgasper 

> If this is something that is blocked due to Spark incompatibility.

It just because we haven't implemented `strikethrough` (or del) yet, just like we didn't implement `table` support before but we could implement it via a recent challenge. 

The current `markdown.js` already includes the `strikethrough` (or del) tokenizer regex, see https://github.com/jmgasper/pxscene/blob/topcoder_updates/mime/components/markdown.js#L526

```
inline.gfm = merge({}, inline.normal, {
    ...
    del: /^~~(?=\S)([\s\S]*?\S)~~/,
    ....
  });
```

Do you want me to implement it?

**Comment by jmgasper** [comment]
Yes, please.  Does the current payment cover the work needed to implement this?

**Comment by billsedison** [comment]
Is it fine to bump it to $400? Currently, what we have for the strike-through is only the regex `del: /^~~(?=\S)([\s\S]*?\S)~~/,`, I need to write the remaining code including token extraction and renderer.

**Comment by jmgasper** [comment]
No problem - done.

**Comment by billsedison** [comment]
Thank you
