### ISSUE TITLE
Linux build failing

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxCore#51]
Attached is the Travis-CI log - check the travis.yml file to see what it does for Linux.

This was run against the _windows_port branch.

[log.txt](https://github.com/topcoderinc/pxCore/files/978080/log.txt)

**Comment by cjalmeida** [comment]
I investigated the issue and the build fails when using running the `pxleakcheck_linux.sh` script.

This script runs a memory intensive JS file. After run, it issues a SIGTERM to terminate.

When terminating a garbage collection on node.js is forced. From the backtrace, it seems that forced GC is failing. It seems this is always throwing a SEGFAULT whenever pxscene is terminated. 

This SEGFAULT always happen when we terminate pxscene. The other build scripts seems to be simply ignoring the signal. To reproduce just run `pxscene http://pxscene.org/examples/px-reference/gallery/gallery.js` then close the window.

This does not affect the runtime behavior, though. 

I tried to simply disable the forced GC with no success - the OS would collect any dangling memory on process end anyways. It seems the issue is deeper and I'll need to investigate it further.

**Comment by cjalmeida** [comment]
I'm attaching the backtrace and a valgrind log.

From the valgrind log you can see a lot of potential issues. All those

- Invalid read of size N
- Conditional jump or move depends on uninitialised value
- Invalid free() / delete / delete[] / realloc()
- Address 0x1177caf0 is N bytes inside a block of size M free'd

messages indicate unsafe or invalid access that could throw a segmentation fault given the opportunity.

I'm not sure if this is related to this particular issue but it's always good practice to keep Valgrind happy.

[bt.txt](https://github.com/topcoderinc/pxCore/files/979286/bt.txt)
[valgrind.txt](https://github.com/topcoderinc/pxCore/files/979287/valgrind.txt)
